services:
  storefront:
    image: ghcr.io/bezaleel22/kutchey-store/storefront:latest
    ports:
      - 3000:3000
    command: ["bun", "run", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password

  server:
    image: ghcr.io/bezaleel22/kutchey-store/server:latest
    ports:
      - 3000:3000
    command: ["bun", "run", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password
  
  worker:
    image: ghcr.io/bezaleel22/kutchey-store/server:latest
    command: ["bun", "run", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: vendure
      DB_USERNAME: postgres
      DB_PASSWORD: password
  
  database:
    image: postgres:16-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure
