services:
  seeding:
    build:
      context: .
    command: [npm, run, init]
    env_file: "./.env"
      
  server:
    build:
      context: .
    command: [npm, run, start:server]
    depends_on:
      - database
    env_file: "./.env"

  worker:
    build:
      context: .
    command: [npm, run, start:worker]
    depends_on:
      - database
    env_file: "./.env"

  database:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vendure